run_dir: "./results/clevr/models/original/attr_net_less_data"
dataset: "clevr"
load_checkpoint_path: null
ann_path: "./results/clevr/original/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr/original/images.h5"
attr_names: ["color", "shape", "material", "size"]
output_dims: [8, 3, 2, 2]
batch_size: 50
num_workers: 4
filename: "model_14"

#training configuration
train_size: 900
val_size: 100
learning_rate: 0.002
seed: 54321
concat_img: false
max_epochs: 50
precision: 32
dev: False
desc: "Run attribute extractor with 1/4 of training data"

# test configuration
test_img_h5: "data/clevr/constraint_1234_test/images.h5"
test_ann_path: "./results/clevr_val/original/constraint_1234/proposals.json"
model_path: './results/clevr/models/original/attr_net_less_data/model_14.ckpt'
attr_map_path: 'G:/My Drive/Research/data/Clevr_mini/clevr_attr_map.json'
use_proba: true
output_path: './results/clevr_val/original/constraint_1234/data_14/attr_scenes.json'