run_dir: "./results/clevr/models/original/attr_net_coord_with_less_data"
dataset: "clevr"
load_checkpoint_path: null
ann_path: "./results/clevr/original/proposals.json"
img_h5: "data/clevr/original/images.h5"
attr_names: ["color", "shape", "material", "size", "x", "y"]
output_dims: [8, 3, 2, 2, 1, 1]
batch_size: 50
num_workers: 4
include_coords: true
filename: "model_0375"

#training configuration
train_size: 1350
val_size: 150
learning_rate: 0.002
concat_img: true
max_epochs: 50
precision: 32
dev: False
desc: "Run attribute extractor with coordinates and half data"

# test configuration
test_img_h5: "data/clevr/constraint_1234_test/images.h5"
test_ann_path: "./results/clevr_val/constraint_1234/constraint_1234/proposals.json"
model_path: './results/clevr/models/constraint_1234/attr_net_coord/model.ckpt'
attr_map_path: 'G:/My Drive/Research/data/Clevr_mini/clevr_attr_map.json'
use_proba: true
output_path: './results/clevr_val/constraint_1234/constraint_1234/scenes_coord_prob.json'