run_dir: "./results/clevr_block/models/constraint_1234/attr_net_coord_less_data"
dataset: "clevr"
load_checkpoint_path: null
ann_path: "./results/clevr_block/constraint_1234/proposals.json"
img_h5: "data/clevr_block/constraint_1234/images_train.h5"
attr_names: ["color", "shape", "material", "size", "x", "z"]
output_dims: [8, 3, 2, 2, 1, 1]
batch_size: 50
num_workers: 4
include_coords: true
filename: "model_14"

#training configuration
train_size: 1350
val_size: 150
learning_rate: 0.002
concat_img: true
max_epochs: 50
precision: 32
dev: False
desc: "Run attribute extractor with coordinates with half data"

# test configuration
test_img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/constraint_1234_test/images.h5"
test_ann_path: "./results/clevr_block_val/constraint_1234/constraint_1234/proposals.json"
model_path: './results/clevr_block/models/constraint_1234/attr_net_coord/model.ckpt'
attr_map_path: 'C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/clevr_attr_map.json'
use_proba: true
output_path: './results/clevr_block_val/constraint_1234/constraint_1234/scenes_coord_prob.json'