run_dir: "./results/clevr/models/original/rel_net_less_data"
ann_path: "./results/clevr/original/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr/original/images.h5"
num_rels: 4
#used_rels: [0, 2]
batch_size: 16
num_workers: 8
filename: "model_14_202204_rnn"
shuffle_train: False

# training configuration
dev: false
max_epochs: 24
precision: 32
train_size: 900
val_size: 100
seed: 202204
learning_rate: 0.002
model_type: "scene_based"
noise_ratio: 0
include_constraint_loss: false # This is not effective if use_sigmoid is false
use_sigmoid: true # If false, this will trigger a 'correct-by-construction run'
#resume_from_checkpoint: './results/clevr/models/rel_net_output_layer/epoch=5-step=8921.ckpt'

# test configuration
test_ann_path: "./results/clevr_val/original/constraint_1234/proposals.json"
test_img_h5: "data/clevr/constraint_1234_test/images.h5"
label_names: ["left", "right", "front", "behind"]
model_path: './results/clevr/models/original/rel_net_less_data/model_14.ckpt'
scenes_path: './results/clevr_val/original/constraint_1234/data_14/attr_scenes.json'
use_proba: True
output_path: './results/clevr_val/original/constraint_1234/data_14/rel_scenes.json'