run_dir: "./results/clevr_block/models/constraint_1234/attr_net"
dataset: "clevr"
load_checkpoint_path: null
ann_path: "./results/clevr_block/constraint_1234/proposals.json"
img_h5: "data/clevr_block/constraint_1234/images_train.h5"
attr_names: ["color", "shape", "material", "size"]
output_dims: [8, 3, 2, 2]
batch_size: 96
num_workers: 4
filename: "model"

#training configuration
train_size: 3600
seed: 202204
val_size: 400
learning_rate: 0.002
concat_img: false
max_epochs: 50
precision: 32
dev: False
desc: "Run attribute extractor with less data"

# test configuration
test_img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/original/images_train.h5"
test_ann_path: "./results/clevr_block/proposals_temp.json"
model_path: './results/clevr_block/models/original/attr_net/model.ckpt'
attr_map_path: 'C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/clevr_attr_map.json'
use_proba: true
output_path: './results/clevr_block_val/original/attr_scenes.json'