run_dir: "./results/clevr/models/rel_noisy"
ann_path: "./results/clevr/proposals.json"
img_h5: "G:/My Drive/Research/data/Clevr_mini/images.h5"
num_rels: 4
#used_rels: [0, 2]
batch_size: 8
num_workers: 4

# training configuration
dev: false
max_epochs: 24
precision: 32
train_size: 3600
learning_rate: 0.002
model_type: "scene_based"
noise_ratio: 0
include_constraint_loss: true # This is not effective if use_sigmoid is false
use_sigmoid: true # If false, this will trigger a 'correct-by-construction run'
#resume_from_checkpoint: './results/clevr/models/rel_net_output_layer/epoch=5-step=8921.ckpt'

# test configuration
test_ann_path: "./results/clevr_val_v2/proposals.json"
test_img_h5: "G:/My Drive/Research/data/Original/images.h5" # G:/My Drive/Research/Fault-Tolerant Neural Networks/Clevr/data/CLEVR_v1.0/images/test_images.h5
label_names: ["left", "right", "front", "behind"] # ["left", "front"]
model_path: './results/clevr/models/rel_noisy/constraint_with_transitivity_3600.ckpt'
scenes_path: './results/clevr_val_v2/attr_scenes.json'
use_proba: true
output_path: './results/clevr_val_v2/rel_scenes_transitivity.json'