run_dir: "./results/clevr_block/models/attr_net"
dataset: "clevr"
load_checkpoint_path: null
ann_path: "./results/clevr_block/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/train_temp/images.h5"
attr_names: ["color", "shape", "material", "size"]
output_dims: [8, 3, 2, 2]
batch_size: 50
num_workers: 4

#training configuration
split_id: 3600
learning_rate: 0.002
concat_img: false
max_epochs: 200
precision: 32
dev: False
desc: "Run attribute extractor with more epoches"

# test configuration
test_img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/constraint_1_2_3_4/images.h5"
test_ann_path: "./results/clevr_block_val/constraint_1_2_3_4/proposals.json"
model_path: './results/clevr_block/models/attr_net/model.ckpt'
attr_map_path: 'C:/Users/chenp/Documents/github/Clevr-Relational/data/clevr_block/clevr_attr_map.json'
use_proba: true
output_path: './results/clevr_block_val/constraint_1_2_3_4/attr_scenes.json'