run_dir: "./results/clevr_block/models/constraint_1234/rel_net_less_data"
ann_path: "./results/clevr_block/original/proposals.json"
img_h5: "data/clevr_block/original/images_train.h5"
num_rels: 4
#used_rels: [0, 2]
batch_size: 8
num_workers: 4

# training configuration
dev: false
max_epochs: 24
precision: 32
train_size: 1800
learning_rate: 0.002
model_type: "scene_based"
noise_ratio: 0
include_constraint_loss: false # This is not effective if use_sigmoid is false
use_sigmoid: true # If false, this will trigger a 'correct-by-construction run'
#resume_from_checkpoint: './results/clevr/models/rel_net_output_layer/epoch=5-step=8921.ckpt'

# test configuration
test_ann_path: "./results/more_objects/block/proposals.json"
test_img_h5: "./data/more_images/block_more_objects/images.h5"
label_names: ["left", "right", "above", "below"] # ["left", "front"]
model_path: 'results/clevr_block/models/constraint_1234/rel_net/model.ckpt'
scenes_path: './results/more_objects/block/attr_scenes.json'
use_proba: True
output_path: './results/more_objects/block/rel_scenes.json'