run_dir: "./results/carla/models/attr_net"
dataset: "carla"
load_checkpoint_path: null
ann_path: "./results/carla/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/carla/images.h5"
attr_names: ["type"]
output_dims: [4]
batch_size: 50
num_workers: 4

#training configuration
split_id: 170
learning_rate: 0.002
concat_img: false
max_epochs: 20
precision: 32
dev: False

# test configuration
test_img_h5: "G:/My Drive/Research/data/Original/images.h5"
test_ann_path: "./results/clevr_val/proposals.json"
model_path: './results/clevr/models/attr_net/model.ckpt'
attr_map_path: 'G:/My Drive/Research/data/Clevr_mini/clevr_attr_map.json'
use_proba: true
output_path: './results/clevr_val/attr_scenes.json'