run_dir: "./results/carla/models/attr_net"
dataset: "carla"
load_checkpoint_path: null
ann_path: "./results/carla/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/carla/images.h5"
attr_names: ["type"]
output_dims: [4]
batch_size: 50
num_workers: 4

#training configuration
split_id: 4000
learning_rate: 0.002
concat_img: false
max_epochs: 20
precision: 32
dev: False

# test configuration
test_img_h5: "./data/carla/images_test.h5"
test_ann_path: "./results/carla_test/proposals.json"
model_path: './results/carla/models/attr_net/model.ckpt'
attr_map_path: './data/carla/schema.json'
use_proba: true
output_path: './results/carla_test/attr_scenes.json'