run_dir: "./results/carla/models/rel_net"
ann_path: "./results/carla/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/carla/images.h5"
num_rels: 4
batch_size: 48
num_workers: 4

# training configuration
dev: false
max_epochs: 30
precision: 32
train_size: 3500
learning_rate: 0.001
dropout_p: 0.1

# test configuration
test_ann_path: "./results/carla_test/proposals.json"
test_img_h5: "./data/carla/images_test.h5"
label_names: ["left", "right", "before", "behind"]
model_path: './results/carla/models/rel_net/model.ckpt'
scenes_path: './results/carla_test/attr_scenes.json'
use_proba: true
output_path: './results/carla_test/rel_scenes.json'