run_dir: "./results/carla_50p/models/rel_net"
ann_path: "./results/carla_50p/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/carla/images.h5"
num_rels: 4
batch_size: 48
num_workers: 4

# training configuration
dev: false
max_epochs: 30
precision: 32
train_size: 4050
learning_rate: 0.001
dropout_p: 0.1
train_type: "scene_based"


# test configuration
test_ann_path: "./results/carla_test_50p/proposals.json"
test_img_h5: "./data/carla/images_test.h5"
label_names: ["left", "right", "before", "behind"]
model_path: './results/carla_50p/models/rel_net/model.ckpt'
scenes_path: './results/carla_test_50p/attr_scenes.json'
use_proba: true
output_path: './results/carla_test_50p/rel_scenes.json'