run_dir: "./results/carla/models/rel_net"
ann_path: "./results/carla/proposals.json"
img_h5: "C:/Users/chenp/Documents/github/Clevr-Relational/data/carla/images.h5"
num_rels: 4
batch_size: 48
num_workers: 4

# training configuration
dev: false
max_epochs: 20
precision: 32
split_id: 170
learning_rate: 0.002

# test configuration
test_ann_path: "./results/clevr_val/proposals.json"
test_img_h5: "G:/My Drive/Research/data/Original/images.h5"
label_names: ["left", "right", "front", "behind"]
model_path: './results/clevr/models/rel_net_output_layer/epoch=9-step=14869.ckpt'
scenes_path: './results/clevr_val/attr_scenes.json'
use_proba: true
output_path: './results/clevr_val/rel_scenes.json'